# Generated by Django 5.0.6 on 2026-06-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escalation", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalationlog",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
