# Generated by Django 5.0.6 on 2026-06-18 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0002_initial"),
        ("patients", "0004_alter_patientprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="patients.patientprofile",
            ),
        ),
    ]
