# Generated by Django 5.0.6 on 2026-06-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0003_medicine_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineAICache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100, unique=True)),
                ("active_ingredient", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
