# Generated by Django 5.0.6 on 2026-06-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_patientprofile_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                default="",
                max_length=10,
            ),
        ),
    ]
