# Generated by Django 5.0.6 on 2026-06-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doses", "0003_initial"),
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp_number", models.CharField(max_length=20)),
                ("message_sent", models.TextField()),
                ("ai_variables", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(default="sent", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dose_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doses.doselog",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patientprofile",
                    ),
                ),
            ],
        ),
    ]
