# Generated by Django 5.0.6 on 2026-06-18 11:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doses", "0003_initial"),
        ("patients", "0004_alter_patientprofile_gender"),
        ("whatsapp", "0002_add_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="whatsappinteraction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "WhatsApp Interaction",
                "verbose_name_plural": "WhatsApp Interactions",
            },
        ),
        migrations.AddField(
            model_name="whatsappinteraction",
            name="external_message_id",
            field=models.CharField(
                blank=True,
                help_text="External WhatsApp/provider message ID for tracking",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="whatsappinteraction",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappinteraction",
            name="ai_variables",
            field=models.JSONField(
                blank=True,
                help_text="AI variables used for message generation",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappinteraction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when message was created",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappinteraction",
            name="dose_log",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated dose log if applicable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_interactions",
                to="doses.doselog",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappinteraction",
            name="message_sent",
            field=models.TextField(help_text="Content of the message sent"),
        ),
        migrations.AlterField(
            model_name="whatsappinteraction",
            name="patient",
            field=models.ForeignKey(
                help_text="Patient who received the message",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_interactions",
                to="patients.patientprofile",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappinteraction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="sent",
                help_text="Delivery status of the message",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappinteraction",
            name="whatsapp_number",
            field=models.CharField(
                help_text="WhatsApp number in E.164 format",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone",
                        message="Enter a valid phone number (E.164 format)",
                        regex="^\\+?[1-9]\\d{1,14}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappinteraction",
            index=models.Index(
                fields=["patient", "-created_at"], name="whatsapp_wh_patient_c812fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappinteraction",
            index=models.Index(
                fields=["status", "-created_at"], name="whatsapp_wh_status_01ea19_idx"
            ),
        ),
    ]
